# Generated by Django 3.2.9 on 2021-11-30 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0004_days_destinations_invoice_package_userdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinations',
            name='Img1',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='destinations',
            name='Img2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='destinations',
            name='Img3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='destinations',
            name='Img4',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
