# Generated by Django 3.2.9 on 2021-12-02 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0012_renderimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='renderimage',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
